version: '3.8'

services:

  web:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - ./html:/var/www/html:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io:ro
    - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
    - 8080:80
    depends_on:
      - wordpress
 
  wordpress:
    container_name: wordpress
    image: wordpress:php7.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    container_name: mysql
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
        
volumes:
  db_data: