version: '3.1'

services:

  mysql:
    container_name: mysql
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always